k9s:
  cluster: minikube
  namespace:
    active: istioinaction
    lockFavorites: false
    favorites:
      - istioinaction
      - default
  view:
    active: po
  featureGates:
    nodeShell: false
  proxy: null
